{'colsample_bytree': 0.6197022995, 'gamma': 2, 'hist_agg': 'median', 'learning_rate': 0.0439901794, 'max_depth': 10, 'min_child_weight': 4, 'n_cases': 40028, 'n_features': 79, 'n_games': 1, 'rounds': 102, 'subsample': 0.7105800489}
Ran out of input
['  File "scripts/meval.sc", line 10, in <module>\n    do_meval.process_cmd_line()\n', '  File "/home/ec2-user/python_misc/ledona/__init__.py", line 21, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/home/ec2-user/python_misc/ledona/slack.py", line 131, in wrapper_notify\n    result = func(*args, **kwargs)\n', '  File "/home/ec2-user/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 598, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/home/ec2-user/fantasy/fantasy_py/calculation/engine.py", line 800, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/home/ec2-user/fantasy/fantasy_py/calculation/engine.py", line 779, in calculate\n    **extra_kwargs)\n', '  File "/home/ec2-user/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 467, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/home/ec2-user/fantasy/fantasy_py/util/hyper_param_tuning.py", line 978, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/home/ec2-user/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/home/ec2-user/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/home/ec2-user/fantasy/fantasy_py/util/hyper_param_tuning.py", line 936, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


{'colsample_bytree': 0.8447355351, 'gamma': 10000, 'hist_agg': 'median', 'learning_rate': 0.0844071061, 'max_depth': 8, 'min_child_weight': 10, 'n_cases': 43405, 'n_features': 79, 'n_games': 1, 'rounds': 142, 'subsample': 0.5641009828}
Ran out of input
['  File "scripts/meval.sc", line 10, in <module>\n    do_meval.process_cmd_line()\n', '  File "/home/ec2-user/python_misc/ledona/__init__.py", line 21, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/home/ec2-user/python_misc/ledona/slack.py", line 131, in wrapper_notify\n    result = func(*args, **kwargs)\n', '  File "/home/ec2-user/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 598, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/home/ec2-user/fantasy/fantasy_py/calculation/engine.py", line 800, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/home/ec2-user/fantasy/fantasy_py/calculation/engine.py", line 779, in calculate\n    **extra_kwargs)\n', '  File "/home/ec2-user/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 467, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/home/ec2-user/fantasy/fantasy_py/util/hyper_param_tuning.py", line 978, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/home/ec2-user/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/home/ec2-user/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/home/ec2-user/fantasy/fantasy_py/util/hyper_param_tuning.py", line 936, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


