{'colsample_bytree': 0.9526508906, 'gamma': 1291, 'hist_agg': 'none', 'learning_rate': 0.0822098787, 'max_depth': 7, 'min_child_weight': 8, 'n_cases': 22495, 'n_features': 397, 'n_games': 6, 'rounds': 98, 'subsample': 0.7425378789}
Ran out of input
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/home/ec2-user/python_misc/ledona/__init__.py", line 22, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/home/ec2-user/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 568, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/home/ec2-user/fantasy/fantasy_py/calculation/engine.py", line 799, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/home/ec2-user/fantasy/fantasy_py/calculation/engine.py", line 778, in calculate\n    **extra_kwargs)\n', '  File "/home/ec2-user/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 476, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/home/ec2-user/fantasy/fantasy_py/util/hyper_param_tuning.py", line 962, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/home/ec2-user/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/home/ec2-user/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/home/ec2-user/fantasy/fantasy_py/util/hyper_param_tuning.py", line 924, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


